### ISSUE TITLE
Petites corrections grammaticales

### ISSUE THREAD

**Issue by Cocoduf** [Falafel65/mavo-locale-fr#1]
Corrections en gras sur les propriétés suivantes:

"delete-confirmation": "Toutes vos données vont être supprimées. Êtes-vous s**û**r ?"
"gh-edit-suggestion-saved-in-profile": "Vos modifications vont être enregistrée**s** [...]"
"gh-edit-suggestion-instructions": "Écrivez une description courte de vos modification**s** [...]"

**Comment by mycaule** [comment]
Quand on clique sur Modifier, on obtient la chaîne de caractères "Modifiering" qui est incorrecte en français.

**Comment by mycaule** [comment]
I think she stopped working on the project.

**Comment by Falafel65** [comment]
Non, je suis encore là ;)
C'est corrigé, merci 👍 

Par contre mycaule, je ne comprends pas le lien direct avec le #319 sur Mavo ?

**Comment by LeaVerou** [comment]
> I think she stopped working on the project.

WTF?! There were commits on Mavo **the day before** your comment (even though it was a holiday). And two days before that. And daily up to a week before that. What more would I need to be doing to be considered actively working on a project in your book?! 🙄

@Falafel65 mavoweb/mavo#319 has just been fixed :)

**Comment by mycaule** [comment]
Get some rest Lea.

**Comment by Falafel65** [comment]
Hey, no fighting here 😀 

Translation updated !
